# Generated by Django 6.0 on 2025-12-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('project_type', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quote_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_attachments', models.BooleanField(default=True)),
                ('max_attachment_size', models.PositiveIntegerField(default=5242880)),
                ('auto_response_message', models.TextField(default='Thank you for requesting a quote! We will review your project and get back to you shortly.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
