# Generated by Django 6.0 on 2025-12-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesettings',
            name='max_attachment_size',
            field=models.PositiveIntegerField(default=10485760),
        ),
    ]
