# Generated by Django 6.0 on 2025-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0003_contactmessage_attachment_alter_contactcta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsettings',
            name='max_attachment_size',
            field=models.PositiveIntegerField(default=10485760),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(default='Area 51/B, Lilongwe, Malawi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='business_hours',
            field=models.TextField(default='Always Open: 6:00 AM - 9:00 PM'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='primeprintsolutions25@outlook.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='+265 996 678 548', max_length=20),
        ),
    ]
