# Generated by Django 6.0 on 2025-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0004_alter_contactformsettings_max_attachment_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
