# Generated by Django 6.0 on 2025-12-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='message_1',
            field=models.CharField(default='Quality prints that speak volumes', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='message_2',
            field=models.CharField(default='Fast turnaround, guaranteed results', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='message_3',
            field=models.CharField(default='Sustainable printing solutions', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('intro', 'Intro Section'), ('service', 'Service Highlights'), ('testimonials', 'Testimonials'), ('featured_projects', 'Featured Projects'), ('company_profile', 'Company Profile'), ('certifications', 'Certifications'), ('cta', 'Call To Action')], max_length=50, unique=True),
        ),
    ]
