# Generated by Django 6.0 on 2025-12-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_herosection_message_1_herosection_message_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('intro', 'Intro Section'), ('service', 'Service Highlights'), ('featured_projects', 'Featured Projects'), ('company_profile', 'Company Profile'), ('testimonials', 'Testimonials'), ('certifications', 'Certifications'), ('cta', 'Call To Action')], max_length=50, unique=True),
        ),
    ]
