# Generated by Django 6.0 on 2025-12-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_calltoaction_id_alter_certification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introsection',
            name='clients_satisfied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='introsection',
            name='delivered_projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='introsection',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
