# Generated by Django 6.0 on 2025-12-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_introsection_clients_satisfied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introsection',
            name='clients_satisfied',
            field=models.PositiveIntegerField(default=0, help_text='Percentage value (0-100)', max_length=100),
        ),
        migrations.AlterField(
            model_name='introsection',
            name='delivered_projects',
            field=models.PositiveIntegerField(default=0, help_text='Total number of projects delivered'),
        ),
        migrations.AlterField(
            model_name='introsection',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Number of years in business'),
        ),
    ]
