# Generated by Django 6.0 on 2025-12-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_introsection_clients_satisfied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introsection',
            name='clients_satisfied',
            field=models.PositiveIntegerField(default=0, help_text='Percentage value (0-100)'),
        ),
    ]
