# Generated by Django 6.0 on 2025-12-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_introsection_clients_satisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='button_link',
            field=models.CharField(default='/request-quote', max_length=50),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='default_button_link',
            field=models.CharField(default='/request-quote', max_length=50),
        ),
    ]
