# Generated by Django 6.0 on 2025-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0003_alter_aboutpagesection_id_alter_companyhistory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofilesection',
            name='clients_served',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofilesection',
            name='projects_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofilesection',
            name='team_Members_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofilesection',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
