# Generated by Django 6.0 on 2025-12-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_alter_certificationcta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationcta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificationnotice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificationpageintro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificationpagesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
