# Generated by Django 6.0.3 on 2026-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_alter_certificationcta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationcta',
            name='button_link',
            field=models.CharField(default='/contact', max_length=255),
        ),
    ]
