# Generated by Django 6.0 on 2025-12-24 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome/React Icons class or icon name', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Ready to get started with your printing project?', max_length=255)),
                ('button_text', models.CharField(default='Get Quote', max_length=100)),
                ('button_link', models.URLField(default='/contact')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Services', max_length=255)),
                ('subtitle', models.TextField(help_text='Short description of services offered')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('intro', 'Page Intro'), ('categories', 'Service Categories'), ('featured_services', 'Featured Services'), ('all_services', 'All Services'), ('process', 'Our Process'), ('cta', 'Call To Action')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('default_enabled', models.BooleanField(default=True)),
                ('default_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Brief description for listings')),
                ('full_description', models.TextField(help_text='Detailed description for service page')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome/React Icons class or icon name', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='servicespage/services/')),
                ('features', models.JSONField(default=list, help_text='List of key features as JSON array')),
                ('pricing_info', models.CharField(blank=True, help_text='Basic pricing information', max_length=200)),
                ('turnaround_time', models.CharField(blank=True, help_text='Typical turnaround time', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='servicespage.servicecategory')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='FontAwesome/React Icons class or icon name', max_length=100)),
                ('estimated_time', models.CharField(blank=True, help_text='Estimated time for this step', max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='servicespage.service')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('service', 'step_number')},
            },
        ),
    ]
