# Generated by Django 6.0 on 2025-12-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0003_alter_portfoliocategory_id_alter_portfoliocta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocta',
            name='button_link',
            field=models.CharField(default='/request-quote', max_length=100),
        ),
    ]
